#!/bin/bash
make clean_arm
make arm && scp bookshelf_arm pi@192.168.1.104:/home/pi/bookshelf_arm
rsync -avz public_html pi@192.168.1.104:/home/pi/bookshelf_arm
ssh 192.168.1.104 -lpi -t 'sudo /bin/bash -c "cd /home/pi/bookshelf_arm && /home/pi/bookshelf_arm/bookshelf_arm"'
